girar-task-make-info-json: add information about task/fail-early flag
Complements: 6cea9a473c86 ("Implement task/fail-early flag")

diff --git a/bin/girar-task-make-info-json b/bin/girar-task-make-info-json
--- a/bin/girar-task-make-info-json
+++ b/bin/girar-task-make-info-json
@@ -14,6 +14,7 @@ printf '{\n'
 printf ' "taskid": %d,\n' "$id"
 printf ' "shared": %s,\n' "$(find gears -maxdepth 0 -path gears -type d -perm -g=w \
 	-printf true -or -printf false 2>/dev/null || echo false)"
+printf ' "fail_early": %s,\n' "$(test -f task/fail-early && echo true || echo false)"
 printf ' "test_only": %s,\n' "$(test -f task/test-only && echo true || echo false)"
 if [ -f task/swift ]; then
 	printf '"swift": true,\n'
