girar-check-perms: extended to check group membership

diff --git a/bin/girar-check-perms b/bin/girar-check-perms
--- a/bin/girar-check-perms
+++ b/bin/girar-check-perms
@@ -1,6 +1,7 @@
 #!/bin/sh -efu
 
 . girar-sh-functions
+. shell-quote
 
 [ -n "${GIRAR_USER-}" ] ||
 	fatal 'GIRAR_USER undefined'
@@ -9,6 +10,7 @@ usage()
 {
 	echo >&2 "$PROG: $*"
 	echo >&2 "usage: $PROG <project name> <binary package repository name>"
+	echo >&2 "    or $PROG @<group name> <binary package repository name>"
 	exit 1
 }
 
@@ -19,6 +21,17 @@ usage()
 
 project_name="$1"; shift
 repo="$1"; shift
+
+is_group=
+case "$project_name" in
+	@*)
+		groups="$project_name"
+		quote_sed_regexp_variable qgroups "$groups"
+		[ -n "${groups#@}" -a "$groups" = "$qgroups" ] ||
+			fatal "$groups: invalid group name"
+		is_group=1
+		;;
+esac
 
 allow()
 {
@@ -35,7 +48,7 @@ deny()
 cd
 
 # Returns:
-# 0 - $GIRAR_USER is allowed to request build of $project_name for binary $repository;
+# 0 - $GIRAR_USER is allowed to request access to $project_name for binary $repository;
 # 1 - otherwise.
 
 repository="$(girar-normalize-repo-name "$repo")" ||
@@ -60,50 +73,52 @@ if [ -s "$conf" ]; then
 	. "$conf"
 fi
 
-# Allowed if package is not listed in acl file.
-if ! acl_line="$(grep "^$project_name[[:space:]]" "$ACL_DIR/list.packages.$repository")"; then
-	if [ -z "${GIRAR_ACL_DENY_UNLISTED-}" ]; then
-		exit=allow
-	else
-		exit=deny
+if [ -z "$is_group" ]; then
+	# Allowed if package is not listed in acl file.
+	if ! acl_line="$(grep "^$project_name[[:space:]]" "$ACL_DIR/list.packages.$repository")"; then
+		if [ -z "${GIRAR_ACL_DENY_UNLISTED-}" ]; then
+			exit=allow
+		else
+			exit=deny
+		fi
+		$exit "project \`$project_name' is not listed in acl file for repository \`$repository'"
 	fi
-	$exit "project \`$project_name' is not listed in acl file for repository \`$repository'"
-fi
 
-# acl_line format: pkg_name leader [builders]
-set -- ${acl_line}
-[ $# -ge 2 ] ||
-	deny "acl file for repository \`$repository' contains invalid acl entry: $acl_line"
-leader="$2"; shift 2
-builders="$*"
+	# acl_line format: pkg_name leader [builders]
+	set -- ${acl_line}
+	[ $# -ge 2 ] ||
+		deny "acl file for repository \`$repository' contains invalid acl entry: $acl_line"
+	leader="$2"; shift 2
+	builders="$*"
 
-# Allowed if $GIRAR_USER is leader.
-[ "$GIRAR_USER" != "$leader" ] ||
-	allow 'project leader'
+	# Allowed if $GIRAR_USER is leader.
+	[ "$GIRAR_USER" != "$leader" ] ||
+		allow 'project leader'
 
-# Allowed if there are no leader
-[ "$leader" != '@nobody' ] ||
-	allow 'project is orphaned'
+	# Allowed if there are no leader
+	[ "$leader" != '@nobody' ] ||
+		allow 'project is orphaned'
 
-# Wildcard builders are allowed.
-case " $builders " in
-	*' * '*|*' @everybody '*)
-		allow 'project leader welcomes random builders' ;;
-esac
+	# Wildcard builders are allowed.
+	case " $builders " in
+		*' * '*|*' @everybody '*)
+			allow 'project leader welcomes random builders' ;;
+	esac
 
-# Separate people and groups.
-groups=
-people=
-for o in ${leader} ${builders}; do
-	[ -z "${o%%@*}" ] &&
-		groups="$groups|$o" ||
-		people="$people $o"
-done
-groups="${groups#|}"
+	# Separate people and groups.
+	groups=
+	people=
+	for o in ${leader} ${builders}; do
+		[ -z "${o%%@*}" ] &&
+			groups="$groups|$o" ||
+			people="$people $o"
+	done
+	groups="${groups#|}"
 
-# Allowed if $GIRAR_USER is listed in $people.
-if printf %s " $people " |fgrep -qs " $GIRAR_USER "; then
-	allow 'approved builder'
+	# Allowed if $GIRAR_USER is listed in $people.
+	if printf %s " $people " |fgrep -qs " $GIRAR_USER "; then
+		allow 'approved builder'
+	fi
 fi
 
 # Expand groups if any.
@@ -117,4 +132,8 @@ if [ -n "$groups" -a -s "$ACL_DIR/list.groups.$repository" ]; then
 	fi
 fi
 
-deny "does not belong to approved builders list: $leader $builders"
+if [ -z "$is_group" ]; then
+	deny "does not belong to approved builders list: $leader $builders"
+else
+	deny "does not belong to group $groups"
+fi
