Introduce plan/i-{src,bin}

diff --git a/gb-sh-functions b/gb-sh-functions
--- a/gb-sh-functions
+++ b/gb-sh-functions
@@ -50,39 +50,37 @@ build_nums()
 
 srpm2i()
 {
-	local f="$1"; shift
-	local i
-	i="$(find build -mindepth 4 -maxdepth 4 -path "build/[1-7]*/*/srpm/$f" -type f |
-		cut -d/ -f2 |sort -nu)"
-	if [ ! -d "build/$i" ]; then
-		echo >&2 " *** cannot find $f in build/[1-7]*/*/srpm/"
+	local f i
+	f="$1"; shift
+	i="$(printf '%s\n' "$f" | join -j 1 -o 2.3 - plan/i-src)"
+	[ -n "$i" -a -d "build/$i" ] || {
+		echo >&2 " *** cannot find $f in the plan"
 		return 1
-	fi
+	}
 	echo "$i"
 }
 
 findrpm()
 {
-	local dir="$1"; shift
-	local f="$1"; shift
-	local p
-	p="$(find build -mindepth 4 -maxdepth 4 -path "build/[1-7]*/*/$dir/$f" -type f |
-		sort -u |head -n1)"
-	if [ ! -f "$p" ]; then
+	local t f p
+	t="$1"; shift
+	f="$1"; shift
+	p="$(printf '%s\n' "$f" | join -j 1 -o 2.2 - plan/i-$t)"
+	[ -f "$p" ] || {
 		echo >&2 " *** cannot find $f in build/[1-7]*/*/$dir/"
 		return 1
-	fi
+	}
 	echo "$p"
 }
 
 findbin()
 {
-	findrpm rpms "$1"
+	findrpm bin "$1"
 }
 
 findsrc()
 {
-	findrpm srpm "$1"
+	findrpm src "$1"
 }
 
 _N="%{name}"
@@ -90,6 +88,8 @@ _VR="%{version}-%{release}"
 _EVR="%|epoch?{%{epoch}:}|$_VR"
 _NVR="%{name}-$_VR"
 _A="%{arch}"
+qf_src="$_N\\t$_EVR\\t$_NVR.src.rpm\\n"
+qf_bin="$_N\\t$_EVR\\t$_A\\t$_NVR.$_A.rpm\\t%{sourcerpm}\\n"
 
 qsrc()
 {
@@ -97,7 +97,7 @@ qsrc()
 	for d; do
 		# src-N  src-EVR  src-F
 		find "$d" -name '*.src.rpm' -execdir \
-			rpmquery --qf "$_N\t$_EVR\t$_NVR.src.rpm\n" -p -- '{}' '+'
+			rpmquery --qf "$qf_src" -p -- '{}' '+'
 	done
 }
 
@@ -107,7 +107,7 @@ qbin()
 	for d; do
 		# bin-N  bin-EVR  bin-A  bin-F  src-F
 		find "$d" -name '*.rpm' -not -name '*.src.rpm' -execdir \
-			rpmquery --qf "$_N\t$_EVR\t$_A\t$_NVR.$_A.rpm\t%{sourcerpm}\n" -p -- '{}' '+'
+			rpmquery --qf "$qf_bin" -p -- '{}' '+'
 	done
 }
 
diff --git a/gb-task-repo-plan b/gb-task-repo-plan
--- a/gb-task-repo-plan
+++ b/gb-task-repo-plan
@@ -7,6 +7,12 @@ fail_if_task_abort_requested
 # Drop old plan if any.
 find plan -type f -delete
 
+fail()
+{
+	stamp_echo >&2 "$*"
+	exit 1
+}
+
 # Make a plan for upgrade: assuming that all new packages go
 # into the repo, find out the existing packages which should
 # be replaced or removed.
@@ -15,19 +21,36 @@ find plan -type f -delete
 
 for i in $(build_nums); do
 	for arch in $GB_ARCH; do
-		if [ -d "build/$i/$arch/srpm" -o ! -s "build/$i/$arch/excluded" ]; then
-			qsrc build/$i/$arch/srpm/
-		fi
+		dir=build/$i/$arch/srpm
+		[ -d "$dir" -o ! -s "build/$i/$arch/excluded" ] ||
+			continue
+		find $dir/ -mindepth 1 -maxdepth 1 \
+			-name '*.src.rpm' -type f \
+			-printf '%f\t%p\t'$i'\n' # filename pathname subtask
 	done
-done >$tmpdir/new.src
+done > $tmpdir/i-src
+
+# sort by filename to filter out duplicates
+sort -u -k1,1 $tmpdir/i-src > plan/i-src
+cut -f2 plan/i-src > $tmpdir/i-src-F
+sort -o $tmpdir/i-src-F{,}
+xargs -r rpmquery --qf "$qf_src" -p -- < $tmpdir/i-src-F > $tmpdir/new.src
 
 for i in $(build_nums); do
 	for arch in $GB_ARCH; do
-		if [ -d "build/$i/$arch/rpms" -o ! -s "build/$i/$arch/excluded" ]; then
-			qbin build/$i/$arch/rpms/
-		fi
+		dir=build/$i/$arch/rpms
+		[ -d "dir" -o ! -s "build/$i/$arch/excluded" ] ||
+			continue
+		find $dir/ -mindepth 1 -maxdepth 1 \
+			-name '*.rpm' -not -name '*.src.rpm' -type f \
+			-printf '%f\t%p\t'$i'\n' # filename pathname subtask
 	done
-done >$tmpdir/new.bin
+done > $tmpdir/i-bin
+# sort by filename to filter out duplicates
+sort -u -k1,1 $tmpdir/i-bin > plan/i-bin
+cut -f2 plan/i-bin > $tmpdir/i-bin-F
+sort -o $tmpdir/i-bin-F{,}
+xargs -r rpmquery --qf "$qf_bin" -p -- < $tmpdir/i-bin-F > $tmpdir/new.bin
 
 for i in $(package_nums); do
 	[ -s gears/$i/copy_repo ] ||
@@ -46,14 +69,12 @@ make_repo_table '' old
 sort -k1,1 -o old.src{,}
 join -v1 del.pkg old.src >del.missing
 if [ -s del.missing ]; then
-	stamp_echo >&2 "FAILED to delete non-existent packages: $(cat del.missing)"
-	exit 1
+	fail "FAILED to delete non-existent packages: $(cat del.missing)"
 fi
 sort -k1,1 -o new.src{,}
 join -o 1.1 del.pkg new.src >del.new
 if [ -s del.new ]; then
-	stamp_echo >&2 "FAILED to delete just built packages: $(cat del.new)"
-	exit 1
+	fail "FAILED to delete just built packages: $(cat del.new)"
 fi
 
 mktable new
@@ -146,6 +167,22 @@ if [ -s "$GB_REPO_DIR/files/list/bin.list" ]; then
 fi
 
 cut -f3 plan/{add,rm}-bin | sort -u > plan/change-arch
+
+# do some consistency checks, just in case
+[ -s plan/change-arch ] ||
+	fail 'cowardly refusing to create an empty plan'
+
+cut -f3 plan/add-src > $tmpdir/add-src-F
+sort -o $tmpdir/add-src-F{,}
+cut -f1 plan/i-src > $tmpdir/i-src-F
+cmp -s $tmpdir/add-src-F $tmpdir/i-src-F ||
+	fail 'oops, plan/add-src and plan/i-src do not match'
+
+cut -f4 plan/add-bin > $tmpdir/add-bin-F
+sort -o $tmpdir/add-bin-F{,}
+cut -f1 plan/i-bin > $tmpdir/i-bin-F
+cmp -s $tmpdir/add-bin-F $tmpdir/i-bin-F ||
+	fail 'oops, plan/add-bin and plan/i-bin do not match'
 
 n_add=$(cat plan/add-src |wc -l)
 n_rm=$(cat plan/rm-src |wc -l)
