gb-task-repo-elfsym: Turn off global cutout switch in case of ENOMEM in bad_elf_symbols_dircmp.pl
There is a not yet reproducable error which make the whole system less
reliable:
http://lists.altlinux.org/pipermail/sisyphus-incominger/2009-August/235771.html
http://lists.altlinux.org/pipermail/sisyphus-incominger/2009-August/235772.html

I hope that halted system with frozen environment will help to catch the bug.

diff --git a/gb-task-repo-elfsym b/gb-task-repo-elfsym
--- a/gb-task-repo-elfsym
+++ b/gb-task-repo-elfsym
@@ -14,10 +14,13 @@ cd "$tmpdir"
 
 for arch in i586 x86_64; do
 	bad_elf_symbols_dircmp.pl {"$repo1","$repo2"}/$arch/RPMS.classic >$arch-bes.plus 3>$arch-bes.minus ||
-		echo 1 >>FAIL &
+		echo $? >>FAIL &
 done
 wait
 if [ -s FAIL ]; then
+	if fgrep -qsx 12 FAIL; then
+		echo "${0##*/} failed in $PWD" >>"$GB_HOME/STOP"
+	fi
 	exit 1
 fi
 
