gb-task-build: cannot use TMPDIR here (overriding TMPDIR is evil)

diff --git a/gb-task-build b/gb-task-build
--- a/gb-task-build
+++ b/gb-task-build
@@ -5,17 +5,19 @@
 id="$1"; shift
 cd "$GB_TASKS/$id"
 
-. tmpdir.sh
+FAIL=`mktemp`
 
 for arch in i586 x86_64; do
 	$0-arch "$id" "$arch" ||
-		echo "$arch build failed" >$TMPDIR/FAIL &
+		echo "$arch build failed" >"$FAIL" &
 	sleep 9
 done
 
 wait
 
-if [ -s $TMPDIR/FAIL ]; then
-	cat >&2 $TMPDIR/FAIL
+if [ -s "$FAIL" ]; then
+	cat >&2 "$FAIL"
+	rm "$FAIL"
 	exit 1
 fi
+rm "$FAIL"
