gb-task-check-lastchange: handle kernel-modules-* specially

diff --git a/gb-task-check-lastchange b/gb-task-check-lastchange
--- a/gb-task-check-lastchange
+++ b/gb-task-check-lastchange
@@ -22,11 +22,19 @@ check()
 	changelog "$1" >$tmpdir/c1
 	changelog "$2" >$tmpdir/c2
 	lastchange=$(head -1 $tmpdir/c1)
-	if ! fgrep -qs -x -e "${lastchange:?}" $tmpdir/c2; then
-		echo "${2##*/}: missing last changelog entry from ${1##*/}:"
-		echo "* $lastchange"
-		rc=1
-	fi >&2
+	if fgrep -qs -x -e "${lastchange:?}" $tmpdir/c2; then
+		return
+	fi
+	# Last changelog entry generated by kernel-build-tools?
+	if echo "${1##*/}" |egrep -qs -x 'kernel-modules-.+\.[0-9]+\.[0-9]+\.src\.rpm'; then
+		lastchange=$(head -2 $tmpdir/c1 |tail -1)
+		if fgrep -qs -x -e "${lastchange:?}" $tmpdir/c2; then
+			return
+		fi
+	fi
+	echo >&2 "${2##*/}: missing last changelog entry from ${1##*/}:"
+	echo >&2 "* $lastchange"
+	rc=1
 }
 
 join -o 1.3,2.3 plan/{rm,add}-src >$tmpdir/F1+F2
