gb-task-acl: check ACL using girar-check-perms

diff --git a/gb-task-acl b/gb-task-acl
--- a/gb-task-acl
+++ b/gb-task-acl
@@ -1,9 +1,32 @@
 #!/bin/sh -efu
 
+. gb-repo-conf
+
 packages=$(cut -f1 plan/{rm,add}-src)
 packages=$(echo "$packages" |sort -u)
 
-for pkg in $packages; do
-	echo >&2 "checking ACL for package $pkg"
-	# TODO: check ACL
+src2i()
+{
+	local src="$1"; shift
+	cd build
+	set +f
+	set -- [1-9]*/*/srpm/"$src"
+	[ -f "$1" ]
+	local IFS=/
+	set -- $1
+	echo "$1"
+}
+
+rc=0
+
+for src in $packages; do
+	i=$(src2i "$src")
+	u=$(sed -n 's/.*<\(.*\)@.*/\1/p' gears/$i/tag_author)
+	if ! out=$(GIRAR_USER="$u" girar-check-perms "$src" "$GB_REPO_NAME" 2>&1); then
+		echo "$out"
+		echo "pkg=$src author=$u repo=$GB_REPO_NAME: ACL check failed"
+		rc=1
+	fi >&2
 done
+
+exit $rc
