Implement src.rpm support

diff --git a/gb-task-check-girar b/gb-task-check-girar
--- a/gb-task-check-girar
+++ b/gb-task-check-girar
@@ -5,13 +5,6 @@
 
 rc=0
 
-set_GIT_DIR()
-{
-	local sym="$(printf %s "$N" |cut -c1)"
-	GIT_DIR="$GB_GEARS_DIR/$sym/$N.git"
-	export GIT_DIR
-}
-
 fail()
 {
 	stamp_echo >&2 "error: $*"
@@ -26,32 +19,8 @@ check_inheritance()
 	[ -z "$(GIT_ALTERNATE_OBJECT_DIRECTORIES="${1-}" git log -n1 --pretty=format:1 ^"$new_id" "$old_id")" ]
 }
 
-girar_check()
+girar_check_git()
 {
-	local N="$1" i="$2"; shift 2
-	local GIT_DIR old_commit_id
-
-	set_GIT_DIR
-
-	if ! old_commit_id="$(git rev-parse --verify "heads/$GB_REPO_NAME^{commit}" 2>/dev/null)"; then
-		# first time push to this branch
-		return 0
-	fi
-
-	# update of existing commit, check inheritance
-
-	if [ -s gears/$i/copy_repo ]; then
-		# copy from another branch
-		local copy_repo copy_commit_id
-		copy_repo="$(cat gears/$i/copy_repo)"
-		copy_commit_id="$(git rev-parse --verify "heads/$copy_repo^{commit}" 2>/dev/null)" ||
-			{ fail "$GIT_DIR contains \"$GB_REPO_NAME\" branch, but does not contain \"$copy_repo\" branch"; return; }
-		check_inheritance "$copy_commit_id" "$old_commit_id" ||
-			fail "$GIT_DIR branch \"$copy_repo\" is not inherited from branch \"$GB_REPO_NAME\""
-		return 0
-	fi
-
-	# build from gear
 	local new_tag_id tag_name old_tag_id
 	new_tag_id="$(cat "gears/$i/tag_id")"
 	tag_name="$(cat "gears/$i/tag_name")"
@@ -67,6 +36,51 @@ girar_check()
 		{ fail "${dir##*/} tag \"$tag_name\" refers to the same commit as $GIT_DIR branch \"$GB_REPO_NAME\""; return; }
 	check_inheritance "$new_commit_id" "$old_commit_id" "gears/$i/git/objects" ||
 		fail "${dir##*/} tag \"$tag_name\" is not inherited from $GIT_DIR branch \"$GB_REPO_NAME\""
+}
+
+girar_check_srpm()
+{
+	fail "$GIT_DIR already contains \"$GB_REPO_NAME\" branch"
+}
+
+girar_check_copy()
+{
+	local copy_repo copy_commit_id
+	copy_repo="$(cat gears/$i/copy_repo)"
+	if ! copy_commit_id="$(git rev-parse --verify "heads/$copy_repo^{commit}" 2>/dev/null)"; then
+		fail "$GIT_DIR already contains \"$GB_REPO_NAME\" branch, but does not contain \"$copy_repo\" branch"
+		return
+	fi
+	check_inheritance "$copy_commit_id" "$old_commit_id" ||
+		fail "$GIT_DIR branch \"$copy_repo\" is not inherited from branch \"$GB_REPO_NAME\""
+}
+
+girar_check()
+{
+	local N="$1" i="$2"; shift 2
+	local GIT_DIR old_commit_id
+
+	set_GIT_DIR "$GB_GEARS_DIR" "$N"
+
+	if ! old_commit_id="$(git rev-parse --verify "heads/$GB_REPO_NAME^{commit}" 2>/dev/null)"; then
+		# first time push to this branch
+		return 0
+	fi
+
+	# update of existing commit, check inheritance
+
+	if [ -s "gears/$i/dir" ]; then
+		# build from gear
+		girar_check_git
+	elif [ -s "gears/$i/srpm" ]; then
+		# build from srpm
+		girar_check_srpm
+	elif [ -s "gears/$i/copy_repo" ]; then
+		# copy from another branch
+		girar_check_copy
+	else
+		fail "#$i: source not found"
+	fi
 }
 
 while read -r N EVR F; do
diff --git a/gb-task-commit-girar b/gb-task-commit-girar
--- a/gb-task-commit-girar
+++ b/gb-task-commit-girar
@@ -3,13 +3,6 @@
 . gb-sh-functions
 . gb-sh-conf
 
-set_GIT_DIR()
-{
-	local sym="$(printf %s "$N" |cut -c1)"
-	GIT_DIR="$GB_GEARS_DIR/$sym/$N.git"
-	export GIT_DIR
-}
-
 update_git_timestamp()
 {
 	local s
@@ -19,41 +12,102 @@ update_git_timestamp()
 	touch --date="1970-01-01 $s seconds UTC" "$GIT_DIR"
 }
 
-girar_commit()
+git_fetch()
 {
-	local N="$1" i="$2"; shift 2
-	local GIT_DIR
-	set_GIT_DIR
+	git fetch -q "$@"
+	rm -f "$GIT_DIR/FETCH_HEAD"
+}
 
-	if [ -s gears/$i/copy_repo ]; then
-		# copy from another branch
-		local copy_repo
-		copy_repo="$(cat "gears/$i/copy_repo")"
-		if git rev-parse --verify "heads/$copy_repo" >/dev/null 2>&1; then
-			git branch -f "$GB_REPO_NAME" "heads/$copy_repo"
-			update_git_timestamp
-			stamp_echo >&2 "updated $GIT_DIR branch \"$GB_REPO_NAME\""
-		fi
-		return 0
-	fi
-
+girar_commit_git()
+{
 	local tag_name
 	tag_name="$(cat "gears/$i/tag_name")"
 	if git rev-parse --verify "heads/$GB_REPO_NAME" >/dev/null 2>&1; then
 		# update gear
-		git fetch -q gears/$i/git tag "$tag_name"
+		git_fetch "gears/$i/git" tag "$tag_name"
 		git branch -f "$GB_REPO_NAME" "tags/$tag_name"
-		update_git_timestamp
 		stamp_echo >&2 "updated $GIT_DIR branch \"$GB_REPO_NAME\""
 	else
 		# first time push
 		mkdir -p -- "$GIT_DIR"
 		git init -q --template=/var/empty
-		git fetch -q gears/$i/git tag "$tag_name"
+		git_fetch "gears/$i/git" tag "$tag_name"
 		git branch "$GB_REPO_NAME" "tags/$tag_name"
 		touch -- "$GIT_DIR/git-daemon-export-ok"
-		update_git_timestamp
 		stamp_echo >&2 "created $GIT_DIR branch \"$GB_REPO_NAME\""
+	fi
+	update_git_timestamp
+}
+
+girar_commit_srpm()
+{
+	local srpm tmp_repo="$tmpdir/repo"
+	srpm="$PWD/gears/$i/$(cat "gears/$i/srpm")"
+	rm -rf -- "$tmp_repo"
+	if git rev-parse --verify "refs/heads/$GB_REPO_NAME" >/dev/null 2>&1; then
+		# update gear
+		export -n GIT_DIR
+		git clone -q -s --bare --template=/var/empty "$GIT_DIR" "$tmp_repo/.git"
+		cd "$tmp_repo"
+		git config core.bare false
+		gear-srpmimport -q --import-only --branch="$GB_REPO_NAME" -- "$srpm"
+		git repack -a -d -q
+		cd - >/dev/null
+
+		export GIT_DIR
+		git_fetch "$tmp_repo/.git" "refs/heads/$GB_REPO_NAME:refs/heads/$GB_REPO_NAME"
+		stamp_echo >&2 "updated $GIT_DIR branch \"$GB_REPO_NAME\""
+	else
+		# first time push
+		export -n GIT_DIR
+		mkdir -p -- "$tmp_repo"
+		cd "$tmp_repo"
+		git init -q --template=/var/empty
+		gear-srpmimport -q --import-only --branch="$GB_REPO_NAME" -- "$srpm"
+		git repack -a -d -q
+		cd - >/dev/null
+
+		export GIT_DIR
+		mkdir -p -- "$GIT_DIR"
+		git init -q --template=/var/empty
+		git_fetch "$tmp_repo/.git" "refs/heads/$GB_REPO_NAME:refs/heads/$GB_REPO_NAME"
+		touch -- "$GIT_DIR/git-daemon-export-ok"
+		stamp_echo >&2 "created $GIT_DIR branch \"$GB_REPO_NAME\""
+	fi
+	rm -rf -- "$tmp_repo"
+	update_git_timestamp
+}
+
+girar_commit_copy()
+{
+	local copy_repo
+	copy_repo="$(cat "gears/$i/copy_repo")"
+	if git rev-parse --verify "heads/$copy_repo" >/dev/null 2>&1; then
+		git branch -f "$GB_REPO_NAME" "heads/$copy_repo"
+		stamp_echo >&2 "updated $GIT_DIR branch \"$GB_REPO_NAME\""
+		update_git_timestamp
+	fi
+}
+
+girar_commit()
+{
+	local N="$1" i="$2"; shift 2
+	local GIT_DIR
+
+	if [ -s "gears/$i/dir" ]; then
+		# build from gear
+		set_GIT_DIR "$GB_GEARS_DIR" "$N"
+		girar_commit_git
+	elif [ -s "gears/$i/srpm" ]; then
+		# build from srpm
+		set_GIT_DIR "$GB_ARCHIVE_DIR" "$N"
+		girar_commit_srpm
+	elif [ -s "gears/$i/copy_repo" ]; then
+		# copy from another branch
+		set_GIT_DIR "$GB_GEARS_DIR" "$N"
+		girar_commit_copy
+	else
+		fail "#$i: source not found"
 	fi
 }
 
@@ -61,7 +115,7 @@ girar_obsolete()
 {
 	local N="$1"; shift
 	local GIT_DIR
-	set_GIT_DIR
+	set_GIT_DIR "$GB_GEARS_DIR" "$N"
 	[ -d "$GIT_DIR" ] || return 0
 	if git rev-parse --verify "heads/$GB_REPO_NAME" >/dev/null 2>&1; then
 		git branch -f "old/$GB_REPO_NAME" "$GB_REPO_NAME"
diff --git a/remote/gb-remote-build b/remote/gb-remote-build
--- a/remote/gb-remote-build
+++ b/remote/gb-remote-build
@@ -1,16 +1,22 @@
 #!/bin/sh -efu
 
 arch="$1"; shift
-dir="$1"; shift
+from="$1"; shift
 tag_name="$1"; shift
 tag_author="$1"; shift
+
+if [ -z "${from##*.src.rpm}" ]; then
+	src="$from"
+else
+	src=pkg.tar
+fi
 
 stamp_echo()
 {
 	echo "$(LC_TIME=C date '+%Y-%b-%d %T') :: $*"
 }
 
-I="[$arch] $dir $tag_name: remote"
+I="[$arch] $from${tag_name:+ $tag_name}: remote"
 
 Fatal()
 {
@@ -42,8 +48,8 @@ trap signal_handler HUP INT QUIT PIPE TERM
 tmpdir=$(mktemp -t -d "${0##*/}.XXXXXXXX")
 
 # Step 1: initialize and query hasher chroot.
-setarch "$arch" -- hsh --init --packager="$tag_author" >"$tmpdir"/out 2>&1 ||
-	{ cat "$tmpdir"/out; Fatal "initroot failed"; } >&2
+setarch "$arch" -- hsh --init ${tag_author:+--packager="$tag_author"} >"$tmpdir"/out 2>&1 ||
+	{ cat "$tmpdir"/out; Fatal 'initroot failed'; } >&2
 
 q_bin='%{name}\t%|serial?{%{serial}:}|%{version}-%{release}\t%{arch}\t%{sourcerpm}\t%{sha1header}\n'
 setarch "$arch" -- hsh-run -- rpmquery -a --qf "$q_bin" >"$tmpdir"/chroot_base
@@ -52,16 +58,16 @@ setarch "$arch" -- hsh-run -- rpmquery -a --qf "$q_bin" >"$tmpdir"/chroot_base
 # This will also install all BuildRequires packages.
 cat >"$tmpdir"/save_srpm <<'EOF'
 mkdir ~/SRPMS
-cp -p --target-directory ~/SRPMS/ -- "$@"
+ln --target-directory ~/SRPMS/ -- "$@"
 EOF
 
-setarch "$arch" -- hsh-rebuild --rebuild-prog="$tmpdir"/save_srpm --no-sisyphus-check tmp/pkg.tar \
+setarch "$arch" -- hsh-rebuild --rebuild-prog="$tmpdir"/save_srpm --no-sisyphus-check tmp/"$src" \
 	>build/srpm.log 2>&1 ||
-		{ cat build/srpm.log; Fatal "cannot build src.rpm"; } >&2
+		{ cat build/srpm.log; Fatal 'cannot build src.rpm'; } >&2
 
 srpm=$(set +f; echo hasher/chroot/usr/src/SRPMS/*.src.rpm) &&
 	srpm_name=$(rpmquery --qf '%{NAME}' -p "$srpm") ||
-		Fatal "cannot build valid src.rpm"
+		Fatal 'cannot build valid src.rpm'
 
 # Step 3: examine BuildRequires.
 setarch "$arch" -- hsh-run -- rpmquery -a --qf "$q_bin" >"$tmpdir"/chroot_BR
@@ -103,9 +109,9 @@ find hasher/repo/$arch/RPMS.hasher/ -mindepth 1 -maxdepth 1 -type f -name '*.rpm
 sort -o "$tmpdir"/rpms1{,}
 
 # Step 6: build.
-setarch "$arch" -- hsh-rebuild tmp/pkg.tar >build/log 2>&1 ||
+setarch "$arch" -- hsh-rebuild tmp/"$src" >build/log 2>&1 ||
 	{ . gb-remote-log; buildlog_errors build/log;
-		  Fatal "build failed"; } >&2
+		  Fatal 'build failed'; } >&2
 setarch "$arch" -- hsh-rmchroot
 
 # Step 5: examine repo/ contents after build.
@@ -120,28 +126,28 @@ sort -o "$tmpdir"/rpms2{,}
 comm -23 "$tmpdir"/rpms{1,2} |cut -f2 |cut -d/ -f2 >"$tmpdir"/out
 if [ -s "$tmpdir"/out ]; then
 	cat "$tmpdir"/out
-	Fatal "attempt to replace binary packages"
+	Fatal 'attempt to replace binary packages'
 fi >&2
 comm -23 "$tmpdir"/srpm{1,2} |cut -f2 |cut -d/ -f2 >"$tmpdir"/out
 if [ -s "$tmpdir"/out ]; then
 	cat "$tmpdir"/out
-	Fatal "attempt to replace source packages"
+	Fatal 'attempt to replace source packages'
 fi >&2
 
 # Step 8: save results.
 comm -23 "$tmpdir"/rpms{2,1} |cut -f2 |cut -d/ -f2 >"$tmpdir"/out
-[ -s "$tmpdir"/out ] || Fatal "no binary packages"
+[ -s "$tmpdir"/out ] || Fatal 'no binary packages'
 cut -f1 "$tmpdir"/out >"$tmpdir"/add-bin
 
 comm -23 "$tmpdir"/srpm{2,1} |cut -f2 |cut -d/ -f2 >"$tmpdir"/out
-[ -s "$tmpdir"/out ] || Fatal "no source package"
+[ -s "$tmpdir"/out ] || Fatal 'no source package'
 cut -f1 "$tmpdir"/out >"$tmpdir"/add-src
 
 # Check that we've got (src,bin+) tuple.
 n=$(wc -l <"$tmpdir"/add-src)
 if [ "$n" -ne 1 ]; then
 	cat "$tmpdir"/add-src
-	Fatal "multpile source packages"
+	Fatal 'multpile source packages'
 fi >&2
 
 (cd hasher/repo/$arch/RPMS.hasher
