Implement debuginfo support

diff --git a/gb-task-check-install-arch b/gb-task-check-install-arch
--- a/gb-task-check-install-arch
+++ b/gb-task-check-install-arch
@@ -6,6 +6,10 @@ arch="$1"; shift
 
 . shell-quote
 
+comps="$(set +f && cd "$GB_TMP_REPO_DIR/$arch" && ls -d RPMS.?* |
+	sed 's/^RPMS\.//' | tr -s '[:space:]' ' ')"
+[ -n "$comps" ]
+
 # Prepare remote node for $arch install check.
 # Note that now we use $remote_host:gb-repo, not $GB_REPO_DIR.
 gb-x-rsync-loop -a "$GB_HOME/remote/" "$remote_host:"
@@ -15,6 +19,7 @@ gb-x-ssh "$remote_host" ./gb-remote-plant \
 	"\"$(quote_shell "$GB_REPO_NAME")\"" \
 	"\"$(quote_shell "$remote_home/gb-repo")\"" \
 	"\"$(quote_shell "$arch")\"" \
+	"\"$(quote_shell "$comps")\"" \
 	cache_dir=cache.check-install
 
 # Copy the temporary repo generated by gb-task-gen-testrepo.
@@ -28,13 +33,13 @@ while read -r N EVR A F P I; do
 
 	if [ -f task/swift ]; then
 		if [ -f "install/$N/$arch/chroot_install" ]; then
-			stamp_echo >&2 "[$arch] $N: install check swiftly skipped"
+			stamp_echo >&2 "[$arch] #$I $N: install check swiftly skipped"
 			continue
 		fi
 	fi
 
 	if [ -f task/abort ]; then
-		stamp_echo >&2 "[$arch] $N: install check ABORTED"
+		stamp_echo >&2 "[$arch] #$I $N: install check ABORTED"
 		rc=1
 		break
 	fi
@@ -44,12 +49,12 @@ while read -r N EVR A F P I; do
 	gb-x-rsync-loop -qrlt --delete -- "install/$N/$arch/" "$remote_host:install/"
 
 	if gb-x-ssh "$remote_host" ./gb-remote-check-install \
-	       "$GB_REPO_NAME" "$arch" "$N" "$EVR" "$A" "$F" </dev/null; then
+	       "$GB_REPO_NAME" "$arch" "$N" "$EVR" "$A" "$F" "$I" </dev/null; then
 		# copy install chroot identification from remote side
 		gb-x-rsync-loop -qrlt --delete -- "$remote_host:install/" "install/$N/$arch/"
 	else
 		rm -rf "install/$N/$arch"
-		stamp_echo >&2 "[$arch] $N: install check FAILED"
+		stamp_echo >&2 "[$arch] #$I $N: install check FAILED"
 		rc=1
 	fi
 done <plan/add-bin
diff --git a/gb-y-repo-regen-basedir b/gb-y-repo-regen-basedir
--- a/gb-y-repo-regen-basedir
+++ b/gb-y-repo-regen-basedir
@@ -21,7 +21,7 @@ if [ -n "$bloat" ]; then
 else
 	# Final repo: need to scan for useful files.
 	for arch in $GB_ARCH noarch; do
-		gb-x-useful-files "$REPO_DIR"/$arch/RPMS.classic >"$tmpdir"/useful-files.$arch ||
+		gb-x-useful-files $(set +f && ls -d "$REPO_DIR"/$arch/RPMS.?*) >"$tmpdir"/useful-files.$arch ||
 			echo 1 >>"$tmpdir"/FAIL &
 	done
 	wait
@@ -42,6 +42,10 @@ fi
 
 mkdir -p "$HOME"/.cache/gen{pkg,src}list
 
+label="${GB_REPO_LABEL:-$GB_REPO_NAME}"
+description="${GB_REPO_DESCRIPTION:-ALT Linux $label}"
+date_s="$(date +%s)"
+
 for arch in $GB_ARCH noarch; do
 	[ -d "$REPO_DIR/$arch" ] || continue
 
@@ -53,9 +57,14 @@ for arch in $GB_ARCH noarch; do
 		maybe_unchanged='--maybe-unchanged'
 	fi
 
-	label="${GB_REPO_LABEL:-$GB_REPO_NAME}"
-	description="${GB_REPO_DESCRIPTION:-ALT Linux $label}"
-	date_s="$(date +%s)"
+	comps="${GB_REPO_COMPONENT_NAMES-}"
+	[ -n "$comps" ] ||
+		comps="$(set +f && cd "$REPO_DIR/$arch" && ls -d RPMS.?* | sed 's/^RPMS\.//')"
+	[ -n "$comps" ] || {
+		echo 1 >>"$tmpdir"/FAIL
+		continue
+	}
+
 	genbasedir "$@" $maybe_unchanged \
 		--cachedir="$HOME"/.cache \
 		--architecture="$arch" \
@@ -70,7 +79,7 @@ for arch in $GB_ARCH noarch; do
 		-s --default-key="$GB_REPO_SIGNER" \
 		--topdir="$REPO_DIR" \
 		--flat --no-oldhashfile --bz2only --mapi \
-		$arch ${GB_REPO_COMPONENT_NAMES:-classic} ||
+		$arch $comps ||
 			echo 1 >>"$tmpdir"/FAIL &
 done
 wait
