gb-task-check-girar: Allow updating exactly the same tag

diff --git a/gb-task-check-girar b/gb-task-check-girar
--- a/gb-task-check-girar
+++ b/gb-task-check-girar
@@ -22,14 +22,16 @@ girar_check()
 
 	if old_id=$(git rev-parse --verify "$GB_GEAR_BRANCH^{commit}" 2>/dev/null); then
 		# real gear
-		local new_id dir tag_name
+		local new_id dir tag_name old_tag_id
 		new_id="$(cat "gears/$i/tag_id")"
 		dir="$(cat "gears/$i/dir")"
 		tag_name="$(cat "gears/$i/tag_name")"
 
-		if git rev-parse --verify "$tag_name" >/dev/null 2>&1; then
-			echo >&2 "error: $GIT_DIR already contains tag $tag_name"
-			rc=1
+		if old_tag_id=$(git rev-parse --verify "$tag_name" 2>/dev/null); then
+			if [ "$old_tag_id" != "$new_id" ]; then
+				echo >&2 "error: $GIT_DIR already contains different tag $tag_name"
+				rc=1
+			fi
 		fi
 
 		new_id="$(git --git-dir="gears/$i/git" rev-parse --verify "$tag_name^{commit}")"
