gb-task-check-build-i: print a broad note in case when sisyphus_check failure is tolerated

diff --git a/gb-task-check-build-i b/gb-task-check-build-i
--- a/gb-task-check-build-i
+++ b/gb-task-check-build-i
@@ -161,9 +161,12 @@ for arch in $GB_ARCH; do
 			continue
 		fi
 		sisyphus_check "$d" && continue
-		is_check_failure_tolerated &&
-			stamp_echo >&2 "$I: sisyphus_check COND-OK" ||
+		if is_check_failure_tolerated; then
+			echo >&2 "$I: the most essential build check failed, but \`$GB_REPO_NAME' is so neglected a repository that nobody cares about such trifles as this."
+			stamp_echo >&2 "$I: sisyphus_check COND-OK"
+		else
 			Fatal 'sisyphus_check FAILED'
+		fi
 	done
 
 	# additional checks for built packages
