gb-task-check-girar (fail, warn): do not prepend the stamp

diff --git a/gb-task-check-girar b/gb-task-check-girar
--- a/gb-task-check-girar
+++ b/gb-task-check-girar
@@ -10,13 +10,13 @@ text=OK
 
 fail()
 {
-	stamp_echo >&2 "error: $*"
+	echo >&2 "error: $*"
 	text=FAILED
 }
 
 warn()
 {
-	stamp_echo >&2 "warning: $*"
+	echo >&2 "warning: $*"
 	[ "$text" = FAILED ] ||
 		text=COND-OK
 }
