gb-task-check-build-i: check for arch-idential src.rpm
$ PATH=$PWD:$PATH ./test-build ~/git.alt/bad-srpm
/tmp/.private/at/tmp.vCZ8TAznJA
created pkg.tar for bad-srpm 1.0-alt1
build bad-srpm 1.0-alt1 for i586
build bad-srpm 1.0-alt1 for x86_64
build bad-srpm 1.0-alt1 for x86_64 OK
build bad-srpm 1.0-alt1 for i586 OK
gb_task_fail: 333 different per-arch srpms: bad-srpm-1.0-alt1.src.rpm bad-srpm-1.0-alt2.src.rpm
$

diff --git a/test-build b/test-build
--- a/test-build
+++ b/test-build
@@ -25,12 +25,13 @@ done
 
 gb_task_fail()
 {
-	echo "gb_task_fail: $*"
+	echo "gb_task_fail: $*" >&2
 	exit 1
 }
 export -f gb_task_fail
 
 gb-task-pkgtar 333
 gb-task-build 333
+gb-task-check-build 333
 
 find build/ -type f |sort
