amqp: call progress event hooks for each build stage

diff --git a/gb/gb-task-build-arch b/gb/gb-task-build-arch
--- a/gb/gb-task-build-arch
+++ b/gb/gb-task-build-arch
@@ -8,5 +8,11 @@ arch="$1"; shift
 rm -rf "build/repo/$arch"
 
 for i in $(src_nums); do
-	$0-i "$arch" "$i"
+	gb-x-girar hook-event subtask progress "$id" "$i" "${0##*/gb-}" "started" "$arch" ||:
+	if $0-i "$arch" "$i"; then
+		gb-x-girar hook-event subtask progress "$id" "$i" "${0##*/gb-}" "processed" "$arch" ||:
+	else
+		gb-x-girar hook-event subtask progress "$id" "$i" "${0##*/gb-}" "failed" "$arch" ||:
+		exit 1
+	fi
 done
diff --git a/gb/gb-task-check-acl b/gb/gb-task-check-acl
--- a/gb/gb-task-check-acl
+++ b/gb/gb-task-check-acl
@@ -4,15 +4,20 @@
 
 fail_if_task_abort_requested
 
-id=$(cat task/id)
+id="$(cat task/id)"
+
+gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "started" ||:
 gb-x-girar check-task-perms "$id" && rc=0 || rc=1
 
 if [ "$rc" = 0 ]; then
 	text=OK
+	gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "processed" ||:
 elif [ -f task/test-only ]; then
 	text=IGNORED
+	gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "ignored" ||:
 else
 	text=FAILED
+	gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "failed" ||:
 	gb-x-girar task-change-state "$id" EPERM
 fi
 
diff --git a/gb/gb-task-check-build b/gb/gb-task-check-build
--- a/gb/gb-task-check-build
+++ b/gb/gb-task-check-build
@@ -10,29 +10,47 @@ fail_if_task_abort_requested
 
 . gb-sh-tmpdir
 
+id="$(cat task/id)"
+
 fail()
 {
 	printf '%s\n' "$*" >> $tmpdir/errors
 }
 
+gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "started" ||:
+
 # check each built package separately
 for i in $(src_nums) $(copy_nums); do
 	fail_if_task_abort_requested
-	$0-i "$i" || fail "#$i"
+	gb-x-girar hook-event subtask progress "$id" "$i" "${0##*/gb-}" "started" ||:
+	if $0-i "$i"; then
+		gb-x-girar hook-event subtask progress "$id" "$i" "${0##*/gb-}" "processed" ||:
+	else
+		gb-x-girar hook-event subtask progress "$id" "$i" "${0##*/gb-}" "failed" ||:
+		fail "#$i"
+	fi
 done
 
 # check all $arch packages in whole
 for arch in $GB_ARCH; do
 	fail_if_task_abort_requested
-	$0-arch "$arch" || fail "$arch"
+	gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "started" "$arch" ||:
+	if $0-arch "$arch"; then
+		gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "processed" "$arch" ||:
+	else
+		gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "failed" "$arch" ||:
+		fail "$arch"
+	fi
 done
 
 rc=0
 if [ -f $tmpdir/errors ]; then
 	rc=1
 	text="FAILED for: $(sort -t'#' -k2,2n $tmpdir/errors |tr -s '\n' ' ')"
+	gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "failed" ||:
 else
 	text=OK
+	gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "processed" ||:
 fi
 
 stamp_echo >&2 "build check $text"
diff --git a/gb/gb-task-check-girar b/gb/gb-task-check-girar
--- a/gb/gb-task-check-girar
+++ b/gb/gb-task-check-girar
@@ -188,6 +188,9 @@ girar_check()
 	fi
 }
 
+id="$(cat task/id)"
+gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "started" ||:
+
 while read -r N EVR F P I; do
 	girar_check "$N" "$I" </dev/null
 done <plan/add-src
@@ -196,10 +199,13 @@ rc=0
 if [ -f $tmpdir/errors ]; then
 	rc=1
 	text="FAILED for: $(sort -t'#' -k2,2n $tmpdir/errors |tr -s '\n' ' ')"
+	gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "failed" ||:
 elif [ -f $tmpdir/warnings ]; then
 	text="COND-OK for: $(sort -t'#' -k2,2n $tmpdir/warnings |tr -s '\n' ' ')"
+	gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "processed" ||:
 else
 	text=OK
+	gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "processed" ||:
 fi
 
 stamp_echo >&2 "gears inheritance check $text"
diff --git a/gb/gb-task-check-install b/gb/gb-task-check-install
--- a/gb/gb-task-check-install
+++ b/gb/gb-task-check-install
@@ -10,11 +10,18 @@ fail_if_task_abort_requested
 
 . gb-sh-tmpdir
 
+id="$(cat task/id)"
+
+gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "started" ||:
 for arch in ${GB_CHECK_INSTALL_ARCH:-$GB_ARCH}; do
-	$0-arch "$arch" || {
+	gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "started" "$arch" ||:
+	if $0-arch "$arch"; then
+		gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "processed" "$arch" ||:
+	else
 		stamp_echo "[$arch] install check FAILED" >>"$tmpdir"/FAIL
 		task_change_state_to_failing "[$arch]"
-	} &
+		gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "failed" "$arch" ||:
+	fi &
 done
 
 wait
@@ -23,10 +30,14 @@ if [ -s "$tmpdir"/FAIL ]; then
 	cat >&2 "$tmpdir"/FAIL
 	if is_check_failure_tolerated; then
 		echo >&2 "The most essential install check failed, but \`$GB_REPO_NAME' is so neglected a repository that nobody cares about such trifles as this."
+		gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "ignored" ||:
 		exit 0
 	fi
+	gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "failed" ||:
 	exit 1
 fi
+
+gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "processed" ||:
 
 # Do not stamp final OK because per-package install checks are already stamped.
 exit 0
diff --git a/gb/gb-task-check-lastchange b/gb/gb-task-check-lastchange
--- a/gb/gb-task-check-lastchange
+++ b/gb/gb-task-check-lastchange
@@ -114,6 +114,9 @@ check()
 	echo >&2 "* $lastchange"
 }
 
+id="$(cat task/id)"
+gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "started" ||:
+
 join -o 0,1.2,1.3,2.4,2.5 plan/{rm,add}-src >$tmpdir/N+EVR+F1+P+I
 while read -r N EVR F1 P I; do
 	check "$I" "$N" "$EVR" "$GB_REPO_DIR/files/SRPMS/$F1" "$P" </dev/null
@@ -123,10 +126,13 @@ rc=0
 if [ -f $tmpdir/errors ]; then
 	rc=1
 	text="FAILED for: $(sort -t'#' -k2,2n $tmpdir/errors |tr -s '\n' ' ')"
+	gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "failed" ||:
 elif [ -f $tmpdir/warnings ]; then
 	text="COND-OK for: $(sort -t'#' -k2,2n $tmpdir/warnings |tr -s '\n' ' ')"
+	gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "processed" ||:
 else
 	text=OK
+	gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "processed" ||:
 fi
 
 stamp_echo >&2 "srpm inheritance check $text"
diff --git a/gb/gb-task-check-noarch b/gb/gb-task-check-noarch
--- a/gb/gb-task-check-noarch
+++ b/gb/gb-task-check-noarch
@@ -4,19 +4,36 @@
 
 fail_if_task_abort_requested
 
+id="$(cat task/id)"
 rc=0
 text=OK
 
+gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "started" ||:
+
 for i in $(src_nums) $(copy_nums); do
-	$0-i "$i" || {
+	gb-x-girar hook-event subtask progress "$id" "$i" "${0##*/gb-}" "started" ||:
+	if $0-i "$i"; then
+		gb-x-girar hook-event subtask progress "$id" "$i" "${0##*/gb-}" "processed" ||:
+	else
 		if is_check_failure_tolerated; then
 			text=IGNORED
+			gb-x-girar hook-event subtask \
+				   progress "$id" "$i" "${0##*/gb-}" "ignored" ||:
 		else
 			rc=1
 			text=FAILED
+			gb-x-girar hook-event subtask \
+				   progress "$id" "$i" "${0##*/gb-}" "failed" ||:
 		fi
-	}
+	fi
 done
 
 stamp_echo >&2 "noarch check $text"
+
+if [ "$rc" = 0 ]; then
+	gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "processed" ||:
+else
+	gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "failed" ||:
+fi
+
 exit $rc
diff --git a/gb/gb-task-gen-ci b/gb/gb-task-gen-ci
--- a/gb/gb-task-gen-ci
+++ b/gb/gb-task-gen-ci
@@ -6,6 +6,9 @@ fail_if_task_abort_requested
 
 . gb-sh-tmpdir
 
+id="$(cat task/id)"
+
+gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "started" ||:
 for arch in $GB_ARCH noarch; do
 	# Regen only if there are $arch packages.
 	grep -F -qsx "$arch" plan/change-arch ||
@@ -22,7 +25,10 @@ wait
 # Fail if at least one arch failed.
 if [ -s "$tmpdir"/FAIL ]; then
 	cat >&2 "$tmpdir"/FAIL
+	gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "failed" ||:
 	exit 1
 fi
+
+gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "processed" ||:
 
 stamp_echo >&2 'created contents_index files'
diff --git a/gb/gb-task-gen-hash b/gb/gb-task-gen-hash
--- a/gb/gb-task-gen-hash
+++ b/gb/gb-task-gen-hash
@@ -6,6 +6,10 @@ fail_if_task_abort_requested
 
 . gb-sh-tmpdir
 
+id="$(cat task/id)"
+
+gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "started" ||:
+
 # src hash file
 $0-src ||
 	stamp_echo "[src] FAILED to create hash file" >> "$tmpdir"/FAIL &
@@ -23,7 +27,10 @@ wait
 # Fail if at least one subcommand failed.
 if [ -s "$tmpdir"/FAIL ]; then
 	cat >&2 "$tmpdir"/FAIL
+	gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "failed" ||:
 	exit 1
 fi
+
+gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "processed" ||:
 
 stamp_echo >&2 "created hash files: $(cd plan && set +f && ls *.hash.xz |sed 's/\.hash\.xz$//')"
diff --git a/gb/gb-task-repo-check-provides b/gb/gb-task-repo-check-provides
--- a/gb/gb-task-repo-check-provides
+++ b/gb/gb-task-repo-check-provides
@@ -68,6 +68,9 @@ dump_dups()
 		sort
 }
 
+id="$(cat task/id)"
+gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "started" ||:
+
 check_arch=
 if grep -Fqsx noarch plan/change-arch; then
 	check_arch="$GB_ARCH" # a change in noarch affects all arches
@@ -171,14 +174,17 @@ if [ -s plus ]; then
 	if is_check_failure_tolerated; then
 		rc=0
 		text=IGNORED
+		gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "ignored" ||:
 	else
 		rc=1
 		text=FAILED
+		gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "failed" ||:
 	fi
 	show_changes new plus 'NEW duplicate provides detected:' >&2
 else
 	rc=0
 	text=OK
+	gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "processed" ||:
 fi
 
 if [ -s minus ]; then
diff --git a/gb/gb-task-repo-elfsym b/gb/gb-task-repo-elfsym
--- a/gb/gb-task-repo-elfsym
+++ b/gb/gb-task-repo-elfsym
@@ -16,6 +16,9 @@ repo2="$GB_TMP_REPO_DIR"
 
 . gb-sh-tmpdir
 
+id="$(cat task/id)"
+gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "started" ||:
+
 cached_arches=
 for arch in $GB_ARCH; do
 	grep -Fqsx $arch plan/change-arch ||
@@ -42,6 +45,7 @@ if [ -s "$tmpdir/FAIL" ]; then
 		halt_build_queue
 	fi
 	stamp_echo >&2 "ELF symbols check FAILED"
+	gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "failed" ||:
 	exit 1
 fi
 
@@ -92,4 +96,9 @@ EOF
 fi
 
 stamp_echo >&2 "[${checked_arches# }] ELF symbols check $text"
+if [ "$rc" = 0 ]; then
+	gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "processed" ||:
+else
+	gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "failed" ||:
+fi
 exit $rc
diff --git a/gb/gb-task-repo-unmets b/gb/gb-task-repo-unmets
--- a/gb/gb-task-repo-unmets
+++ b/gb/gb-task-repo-unmets
@@ -4,6 +4,7 @@
 
 fail_if_task_abort_requested
 
+id="$(cat task/id)"
 repo1="$GB_REPO_DIR"
 repo2="$GB_TMP_REPO_DIR"
 topdir="$PWD"
@@ -48,9 +49,12 @@ dump_unmets()
 
 	wait
 	if [ -s FAIL ]; then
+		gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "failed" ||:
 		exit 1
 	fi
 }
+
+gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "started" ||:
 
 dump_unmets
 dump_unmets checkinstall
@@ -126,6 +130,13 @@ if [ -s unmets.stat ]; then
 	stamp_echo >&2 "unmets:$(cat unmets.stat)"
 fi
 
-[ "$rc" = 0 ] && text=OK || text=FAILED
+if [ "$rc" = 0 ]; then
+	text=OK
+	gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "processed" ||:
+else
+	text=FAILED
+	gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "failed" ||:
+fi
+
 stamp_echo >&2 "dependencies check $text"
 exit $rc
diff --git a/gb/gb-task-save-repo b/gb/gb-task-save-repo
--- a/gb/gb-task-save-repo
+++ b/gb/gb-task-save-repo
@@ -8,6 +8,9 @@ fail_if_task_abort_requested
 
 ln -snf "$GB_REPO_DIR" "build/repo/prev"
 
+id="$(cat task/id)"
+gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "started" ||:
+
 for arch in $GB_ARCH noarch; do
 	$0-arch "$arch" ||
 		stamp_echo "[$arch] FAILED to save apt indices" >>"$tmpdir"/FAIL &
@@ -18,7 +21,9 @@ wait
 # Fail if at least one arch failed.
 if [ -s "$tmpdir"/FAIL ]; then
 	cat >&2 "$tmpdir"/FAIL
+	gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "failed" ||:
 	exit 1
 fi
 
+gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "processed" ||:
 exit 0
diff --git a/gb/gb-y-arch-iterator b/gb/gb-y-arch-iterator
--- a/gb/gb-y-arch-iterator
+++ b/gb/gb-y-arch-iterator
@@ -6,6 +6,9 @@ fail_if_task_abort_requested
 
 . gb-sh-tmpdir
 
+id="$(cat task/id)"
+gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "started" ||:
+
 for arch in $GB_ARCH; do
 	$0-arch "$arch" "$@" || {
 		me=${0##*/}
@@ -20,7 +23,10 @@ wait
 # Fail if at least one arch failed.
 if [ -s "$tmpdir"/FAIL ]; then
 	cat >&2 "$tmpdir"/FAIL
+	gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "failed" ||:
 	exit 1
 fi
+
+gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "processed" ||:
 
 exit 0
diff --git a/gb/gb-y-arepo-arch-iterator b/gb/gb-y-arepo-arch-iterator
--- a/gb/gb-y-arepo-arch-iterator
+++ b/gb/gb-y-arepo-arch-iterator
@@ -6,11 +6,18 @@ fail_if_task_abort_requested
 
 . gb-sh-tmpdir
 
+id="$(cat task/id)"
+gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "started" ||:
+
 for arch in $GB_AREPO_ARCH; do
-	$0-arch "$arch" "$@" || {
+	gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "started" "$arch" ||:
+	if $0-arch "$arch" "$@"; then
+		gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "processed" "$arch" ||:
+	else
 		me=${0##*/}
 		stamp_echo "[$arch] ${me#gb-task-arepo-} FAILED" >>"$tmpdir"/FAIL
-	} &
+		gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "failed" "$arch" ||:
+	fi &
 done
 
 wait
@@ -18,7 +25,10 @@ wait
 # Fail if at least one arch failed.
 if [ -s "$tmpdir"/FAIL ]; then
 	cat >&2 "$tmpdir"/FAIL
+	gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "failed" ||:
 	exit 1
 fi
+
+gb-x-girar hook-event task progress "$id" "${0##*/gb-}" "processed" ||:
 
 exit 0
