gb-task-repo-elfsym: do not use gb-sh-rpmhdrcache
There is no benefit in using gb-sh-rpmhdrcache with bad_elf_symbols_dircmp.pl

diff --git a/gb/gb-task-repo-elfsym b/gb/gb-task-repo-elfsym
--- a/gb/gb-task-repo-elfsym
+++ b/gb/gb-task-repo-elfsym
@@ -27,15 +27,11 @@ for arch in $GB_ARCH; do
 		continue
 	fi
 
-	(
-		. gb-sh-rpmhdrcache
-
-		# Assume that the only component worth checking is "classic".
-		bad_elf_symbols_dircmp.pl \
-				{"$repo1","$repo2"}/$arch/RPMS.classic \
-				> bad_elf_symbols/$arch.new 3> bad_elf_symbols/$arch.old ||
-			echo $? >>"$tmpdir/FAIL"
-	) &
+	# Assume that the only component worth checking is "classic".
+	bad_elf_symbols_dircmp.pl \
+			{"$repo1","$repo2"}/$arch/RPMS.classic \
+			> bad_elf_symbols/$arch.new 3> bad_elf_symbols/$arch.old ||
+		echo $? >> "$tmpdir/FAIL" &
 done
 [ -z "$cached_arches" ] ||
 	stamp_echo >&2 "[${cached_arches# }] no need to repeat ELF symbols check"
