gb-x-rsync-loop: limit the number of attempts
Endless loop is not the best choice when the remote node went bananas.

diff --git a/gb/gb-x-rsync-loop b/gb/gb-x-rsync-loop
--- a/gb/gb-x-rsync-loop
+++ b/gb/gb-x-rsync-loop
@@ -1,3 +1,11 @@
 #!/bin/sh -efu
 
-while ! rsync --timeout=3600 "$@"; do sleep 1; done
+for i in `seq 0 300`; do
+	rsync --timeout=300 "$@" && i= && break ||
+		sleep 1
+done
+
+[ -z "$i" ] || {
+	echo >&2 "${0##*/}: all attempts failed"
+	exit 1
+}
