gb-y-select-task: handle idle tasks
Skip idle tasks if either $min_iter is positive or
there are non-idle non-test-only tasks in $next_state queue
or in optional extra queues.

diff --git a/gb/gb-y-select-task b/gb/gb-y-select-task
--- a/gb/gb-y-select-task
+++ b/gb/gb-y-select-task
@@ -47,6 +47,10 @@ select_task()
 
 	gb-task-validate-state "$canon_find" || exit
 
+	# if idle iteration number is positive and the task is idle, fail
+	[ "$skip_idle_tasks" = 0 ] ||
+		[ ! -f task/idle ] || exit
+
 	# if task iteration number is less than required minimum, fail
 	local iter
 	iter="$(grep -h '^[1-9][0-9]*$' task/iter)" || exit
@@ -69,6 +73,12 @@ select_task()
 	gb-x-girar task-change-state "$id" "$next_state" ||
 		halt_build_queue
 }
+
+skip_idle_tasks="$min_iter"
+if [ "$skip_idle_tasks" = 0 ]; then
+	gb-y-queues-are-empty "$next_state" "$@" ||
+		skip_idle_tasks=1
+fi
 
 retry=1
 while [ -n "$retry" ]; do
