Add support for 'private' directory
Add 'private' directory to hide git repositories from public view. Only
maintainer may subscribe other users for email notification.

diff --git a/hooks/update.in b/hooks/update.in
--- a/hooks/update.in
+++ b/hooks/update.in
@@ -63,6 +63,12 @@ check_etc_packages()
 		return
 }
 
+check_etc_private()
+{
+	[ "$project" = "etc/private" -a "$1" = "refs/heads/master" ] ||
+		return
+}
+
 validate_distribution_subscription()
 {
 	local where="$1" && shift
@@ -100,55 +106,78 @@ validate_email_list()
 	done
 }
 
+check_distribution()
+{
+	[ -s "$workdir/distribution" ] || return 0
+	local p t n a rest line=0
+	while read -r p t n a rest; do
+		line="$((1+$line))"
+		[ -n "$a" ] ||
+			fatal "email-distribution:$line: insufficient fields."
+		validate_distribution_subscription \
+			"email-distribution:$line" \
+			"$p" "$t" "$n" "$rest"
+		validate_email_list "email-distribution:$line" "$a"
+	done <"$workdir/distribution"
+}
+
+check_subscription()
+{
+	[ -s "$workdir/subscription" ] || return 0
+	local u p t n rest line=0
+	while read -r u p t n rest; do
+		line="$((1+$line))"
+		[ -n "$n" ] ||
+			fatal "email-subscription:$line: insufficient fields."
+		validate_distribution_subscription \
+			"email-subscription:$line" \
+			"$p" "$t" "$n" "$rest"
+		[ "$u" = '*' ] ||
+			{
+				printf %s "$u" |egrep -qs '^[a-z][a-z_0-9]+$' &&
+				[ -d "$GITER_HOME/$u" ]
+			} ||
+			fatal "$where: invalid user pattern: $u"
+	done <"$workdir/subscription"
+}
+
+check_update()
+{
+	>"$workdir/$1"
+	if git-diff-tree --name-only "$3" "$4" -- email-"$1" |
+	   fgrep -qs email-"$1"; then
+		git-cat-file blob "$4:email-$1" 2>/dev/null |
+			egrep '^[[:space:]]*[^#]' >"$workdir/$1"
+	fi
+}
+
 handle_etc_packages()
 {
 	check_etc_packages "$@" || return 0
 
-	local u p t n a line rest
+	local n
 	for n in distribution subscription; do
-		if git-diff-tree --name-only "$2" "$3" -- email-"$n" |
-		   fgrep -qs email-"$n"; then
-			git-cat-file blob "$3:email-$n" 2>/dev/null |
-				egrep '^[[:space:]]*[^#]' >"$workdir/$n"
-		fi
+		check_update "$n" "$@"
 	done
 
-	if [ -f "$workdir/distribution" ]; then
-		line=0
-		while read -r p t n a rest; do
-			line="$((1+$line))"
-			[ -n "$a" ] ||
-				fatal "email-distribution:$line: insufficient fields."
-			validate_distribution_subscription \
-				"email-distribution:$line" \
-				"$p" "$t" "$n" "$rest"
-			validate_email_list "email-distribution:$line" "$a"
-		done <"$workdir/distribution"
-	fi
-
-	if [ -f "$workdir/subscription" ]; then
-		line=0
-		while read -r u p t n rest; do
-			line="$((1+$line))"
-			[ -n "$n" ] ||
-				fatal "email-subscription:$line: insufficient fields."
-			validate_distribution_subscription \
-				"email-subscription:$line" \
-				"$p" "$t" "$n" "$rest"
-			[ "$u" = '*' ] ||
-				{
-					printf %s "$u" |egrep -qs '^[a-z][a-z_0-9]+$' &&
-					[ -d "$GITER_HOME/$u" ]
-				} ||
-				fatal "$where: invalid user pattern: $u"
-		done <"$workdir/subscription"
-	fi
+	check_distribution
+	check_subscription
 
 	for n in distribution subscription; do
-		if [ -f "$workdir/$n" ]; then
+		[ ! -s "$workdir/$n" ] ||
 			cp "$workdir/$n" "@GITER_EMAIL_DIR@/packages/$GITER_USER/"
-		fi
 	done
+}
+
+handle_etc_private()
+{
+	check_etc_private "$@" || return 0
+
+	check_update "distribution" "$@"
+	check_distribution
+
+	[ ! -s "$workdir/distribution" ] ||
+		cp "$workdir/distribution" "@GITER_EMAIL_DIR@/private/$GITER_USER/"
 }
 
 email_new_head()
@@ -230,12 +259,13 @@ email_update_ref()
 }
 
 mailto="$(
-	"@CMDDIR@/find-subscribers" "$project_name" "$ref_style" "$ref_name" |
+	"@CMDDIR@/find-subscribers" "$project_name" "$ref_style" "$ref_name" packages private |
 	tr -s '\n' , |
 	sed -e 's/^,\+//' -e 's/,\+$//' -e 's/,/, /g'
 )"
 [ -n "$mailto" ] ||
 	check_etc_packages "$@" ||
+	check_etc_private "$@" ||
 	exit 0
 
 exit_handler()
@@ -284,6 +314,7 @@ if expr "$2" : '0*$' >/dev/null; then
 else
 	# update ref
 	handle_etc_packages "$@"
+	handle_etc_private "$@"
 	[ -z "$mailto" ] ||
 		email_update_ref "$@" >>"$MSG"
 fi
diff --git a/sbin/giter-add.in b/sbin/giter-add.in
--- a/sbin/giter-add.in
+++ b/sbin/giter-add.in
@@ -33,6 +33,13 @@ if ! readlink -ev "@GITER_PACKAGES_DIR@" &>/dev/null; then
 which will be cloned to \$GITER_HOME/etc/packages.git.
 EOF
 
+if ! readlink -ev "@GITER_PRIVATE_DIR@" &>/dev/null; then
+	error "@GITER_PRIVATE_DIR@: broken symlink"
+	cat>&2 <<EOF
+@GITER_PRIVATE_DIR@ should contain template of git repository
+which will be cloned to \$GITER_HOME/etc/private.git.
+EOF
+
 IDFILE="$(readlink -ev "$IDFILE")" ||
 	fatal "identity file '$IDFILE' not available"
 
@@ -98,6 +105,9 @@ install -d -o "$IT_NAME" -g giter -m755 "$REAL_HOME" ||
 install -d -o "$IT_NAME" -g giter -m755 "$REAL_HOME/packages" ||
 	fatal "$IT_NAME: failed to create $REAL_HOME/packages"
 
+install -d -o "$IT_NAME" -g giter -m751 "$REAL_HOME/private" ||
+	fatal "$IT_NAME: failed to create $REAL_HOME/private"
+
 install -d -o "$IT_NAME" -g wheel -m750 "$REAL_HOME/etc" ||
 	fatal "$IT_NAME: failed to create $REAL_HOME/etc"
 
@@ -106,7 +116,14 @@ git-clone --bare --template=@GITER_TEMPLATES_DIR@ \
 	chown -hR "$IT_NAME:giter" "$REAL_HOME/etc/packages.git" ||
 	fatal "$IT_NAME: failed to setup $REAL_HOME/etc/packages.git"
 
-EMAIL_DIR="@GITER_EMAIL_DIR@/packages"
-mkdir -p "$EMAIL_DIR"
-install -d -o "$IT_NAME" -g giter -m755 "$EMAIL_DIR/$NAME" ||
-	fatal "$IT_NAME: failed to create $EMAIL_DIR/$NAME"
+git-clone --bare --template=@GITER_TEMPLATES_DIR@ \
+	"@GITER_PRIVATE_DIR@" "$REAL_HOME/etc/private.git" &&
+	chown -hR "$IT_NAME:giter" "$REAL_HOME/etc/private.git" &&
+	fatal "$IT_NAME: failed to setup $REAL_HOME/etc/private.git"
+
+for n in packages privastes; do
+	EMAIL_DIR="@GITER_EMAIL_DIR@/$n"
+	mkdir -p "$EMAIL_DIR"
+	install -d -o "$IT_NAME" -g giter -m755 "$EMAIL_DIR/$NAME" ||
+		fatal "$IT_NAME: failed to create $EMAIL_DIR/$NAME"
+done
