hooks/update.in (handle_etc_packages): Handle acl-groups and acl-packages files

diff --git a/hooks/update.in b/hooks/update.in
--- a/hooks/update.in
+++ b/hooks/update.in
@@ -160,6 +160,52 @@ validate_email_subscription()
 	done <"$workdir/subscription"
 }
 
+validate_acl_groups()
+{
+	[ -s "$workdir/groups" ] || return 0
+	local name rest line=0
+	while read -r name rest; do
+		line="$((1+$line))"
+		printf %s "$name" |egrep -qs "$group_name_regexp" ||
+			fatal "acl-groups:$line: invalid group name: $name"
+		set -- ${rest}
+		local u
+		for u; do
+			[ "$u" != '*' ] ||
+				continue
+			printf %s "$u" |egrep -qs '^[a-z][a-z_0-9]+$' &&
+			[ -d "$GIRAR_HOME/$u" ] ||
+				fatal "acl-groups:$line: invalid user name: $u"
+		done
+	done <"$workdir/groups"
+}
+
+validate_acl_packages()
+{
+	[ -s "$workdir/packages" ] || return 0
+	local name rest line=0
+	while read -r name rest; do
+		line="$((1+$line))"
+		printf %s "$name" |egrep -qs "$project_name_regexp" ||
+			fatal "acl-packages:$line: invalid package name: $name"
+		set -- ${rest}
+		local u
+		for u; do
+			[ "$u" != '*' ] ||
+				continue
+			if [ -z "${u##@*}" ]; then
+				[ -n "${u#@}" ] &&
+				printf %s "${u#@}" |egrep -qs "$group_name_regexp" ||
+					fatal "acl-packages:$line: invalid group name: $u"
+				continue
+			fi
+			printf %s "$u" |egrep -qs '^[a-z][a-z_0-9]+$' &&
+			[ -d "$GIRAR_HOME/$u" ] ||
+				fatal "acl-packages:$line: invalid user name: $u"
+		done
+	done <"$workdir/packages"
+}
+
 check_unsupported_update()
 {
 	local re="^($1)\$"; shift
@@ -185,7 +231,9 @@ check_update()
 handle_etc_packages()
 {
 	check_etc_directory packages "$@" || return 0
-	check_unsupported_update 'email-distribution|email-subscription' "$@"
+	check_unsupported_update 'acl-groups|acl-packages|email-distribution|email-subscription' "$@"
+	check_update acl groups "$@"
+	check_update acl packages "$@"
 	check_update email distribution "$@"
 	check_update email subscription "$@"
 
