admin/girar-admin-sh-functions.in (load_identity): allow ssh-ed25519 and ecdsa-sha2-nistp* keys

diff --git a/admin/girar-admin-sh-functions.in b/admin/girar-admin-sh-functions.in
--- a/admin/girar-admin-sh-functions.in
+++ b/admin/girar-admin-sh-functions.in
@@ -36,9 +36,9 @@ load_identity()
 		fatal "$IDFILE: error reading identity file"
 
 	local type
-	type="$(printf %s "$IDENTITY" |head -c7)"
+	type="$(printf %s "$IDENTITY" |head -c20 |cut -d' ' -f1)"
 	case "$type" in
-		ssh-dss|ssh-rsa) ;;
+		ssh-dss|ssh-rsa|ssh-ed25519|ecdsa-sha2-nistp256|ecdsa-sha2-nistp384|ecdsa-sha2-nistp521) ;;
 		*) fatal "$IDFILE: invalid identity file: unrecognized key type" ;;
 	esac
 	[ "$(echo "$IDENTITY" |wc -l)" = 1 ] ||
@@ -51,6 +51,14 @@ load_identity()
 		ssh-dss) [ "$size" = 1024 -o "$size" = 2048 -o "$size" = 4096 ] ||
 				fatal "$IDFILE: invalid $type key size: $size" ;;
 		ssh-rsa) [ "$size" = 2048 -o "$size" = 4096 ] ||
+				fatal "$IDFILE: invalid $type key size: $size" ;;
+		ssh-ed25519) [ "$size" = 256 ] ||
+				fatal "$IDFILE: invalid $type key size: $size" ;;
+		ecdsa-sha2-nistp256) [ "$size" = 256 ] ||
+				fatal "$IDFILE: invalid $type key size: $size" ;;
+		ecdsa-sha2-nistp384) [ "$size" = 384 ] ||
+				fatal "$IDFILE: invalid $type key size: $size" ;;
+		ecdsa-sha2-nistp521) [ "$size" = 521 ] ||
 				fatal "$IDFILE: invalid $type key size: $size" ;;
 	esac
 }
