gb-remote-build: treat all src.rpm build errors on armh as ExcludeArch
armh is an architecture that has far fewer supported packages than other
architectures.  Treat src.rpm build errors on armh as ExcludeArch to
lift unnecessary burden from package maintainers who haven't opted in.

This is a temporary commit until someone implements a better solution.

diff --git a/gb/remote/gb-remote-build b/gb/remote/gb-remote-build
--- a/gb/remote/gb-remote-build
+++ b/gb/remote/gb-remote-build
@@ -128,7 +128,11 @@ hsh-rebuild $build_env_flags --repo-src="$tmpdir"/srpm --query-repackage --no-si
 			exit 0
 		fi
 		sed "s/^/$arch_prefix/" build/srpm.log
-		Fatal 'cannot build src.rpm'
+		[ "$arch" = armh ] ||
+			Fatal 'cannot build src.rpm'
+		echo 'Cannot build src.rpm' > build/excluded
+		stamp_echo >&2 "$I: cannot build src.rpm, but we don't care"
+		exit 0
 	} >&2
 
 # Step 4: examine BuildRequires.
